# Generated by Django 4.0.2 on 2022-03-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Top Wear', 'Top Wear'), ('Bottom Wear', 'Bottom Wear')], max_length=15),
        ),
    ]
